[2022-08-04 00:14:33,727] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: secret_vars.test_conn manual__2022-08-03T21:09:26.332868+00:00 [queued]>
[2022-08-04 00:14:33,731] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: secret_vars.test_conn manual__2022-08-03T21:09:26.332868+00:00 [queued]>
[2022-08-04 00:14:33,731] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 00:14:33,731] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2022-08-04 00:14:33,731] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 00:14:33,737] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): test_conn> on 2022-08-03 21:09:26.332868+00:00
[2022-08-04 00:14:33,740] {standard_task_runner.py:52} INFO - Started process 47079 to run task
[2022-08-04 00:14:33,742] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'secret_vars', 'test_conn', 'manual__2022-08-03T21:09:26.332868+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/task_dag.py', '--cfg-path', '/tmp/tmpula8yump', '--error-file', '/tmp/tmpn2z075ud']
[2022-08-04 00:14:33,742] {standard_task_runner.py:80} INFO - Job 14: Subtask test_conn
[2022-08-04 00:14:33,768] {task_command.py:371} INFO - Running <TaskInstance: secret_vars.test_conn manual__2022-08-03T21:09:26.332868+00:00 [running]> on host ndx-Victus
[2022-08-04 00:14:33,793] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=secret_vars
AIRFLOW_CTX_TASK_ID=test_conn
AIRFLOW_CTX_EXECUTION_DATE=2022-08-03T21:09:26.332868+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-03T21:09:26.332868+00:00
[2022-08-04 00:14:33,796] {base.py:68} INFO - Using connection ID 'mongo_test_hook' for task execution.
[2022-08-04 00:14:33,796] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow/dags/task_dag.py", line 17, in test_conn
    print(hook.find())
TypeError: find() missing 2 required positional arguments: 'mongo_collection' and 'query'
[2022-08-04 00:14:33,798] {taskinstance.py:1415} INFO - Marking task as FAILED. dag_id=secret_vars, task_id=test_conn, execution_date=20220803T210926, start_date=20220803T211433, end_date=20220803T211433
[2022-08-04 00:14:33,803] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task test_conn (find() missing 2 required positional arguments: 'mongo_collection' and 'query'; 47079)
[2022-08-04 00:14:33,833] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-04 00:14:33,845] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
