[2022-08-04 12:22:13,312] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: secret_vars.test_conn manual__2022-08-04T09:22:07.889204+00:00 [queued]>
[2022-08-04 12:22:13,315] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: secret_vars.test_conn manual__2022-08-04T09:22:07.889204+00:00 [queued]>
[2022-08-04 12:22:13,315] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 12:22:13,315] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-08-04 12:22:13,315] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-04 12:22:13,321] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): test_conn> on 2022-08-04 09:22:07.889204+00:00
[2022-08-04 12:22:13,324] {standard_task_runner.py:52} INFO - Started process 61319 to run task
[2022-08-04 12:22:13,325] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'secret_vars', 'test_conn', 'manual__2022-08-04T09:22:07.889204+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/task_dag.py', '--cfg-path', '/tmp/tmp2hvxzhoo', '--error-file', '/tmp/tmpb_8y4unu']
[2022-08-04 12:22:13,326] {standard_task_runner.py:80} INFO - Job 40: Subtask test_conn
[2022-08-04 12:22:13,345] {task_command.py:371} INFO - Running <TaskInstance: secret_vars.test_conn manual__2022-08-04T09:22:07.889204+00:00 [running]> on host ndx-Victus
[2022-08-04 12:22:13,366] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=secret_vars
AIRFLOW_CTX_TASK_ID=test_conn
AIRFLOW_CTX_EXECUTION_DATE=2022-08-04T09:22:07.889204+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-04T09:22:07.889204+00:00
[2022-08-04 12:22:13,368] {base.py:68} INFO - Using connection ID 'mongo_test_hook' for task execution.
[2022-08-04 12:22:14,389] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow/dags/task_dag.py", line 19, in test_conn
    hook(mongo_collection="users", db_name="test")
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow/dags/mongo_inserter.py", line 35, in __call__
    super().update_one(mongo_collection, {"reviewId": data['reviewId']}, doc, db_name)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow/dags/mongo_hook.py", line 184, in update_one
    return collection.update_one(filter_doc, update_doc, **kwargs)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/collection.py", line 1029, in update_one
    common.validate_ok_for_update(update)
  File "/home/ndx/Innowise tasks/Innowise_task_5/airflow_env/lib/python3.8/site-packages/pymongo/common.py", line 587, in validate_ok_for_update
    raise ValueError("update only works with $ operators")
ValueError: update only works with $ operators
[2022-08-04 12:22:14,392] {taskinstance.py:1415} INFO - Marking task as UP_FOR_RETRY. dag_id=secret_vars, task_id=test_conn, execution_date=20220804T092207, start_date=20220804T092213, end_date=20220804T092214
[2022-08-04 12:22:14,398] {standard_task_runner.py:92} ERROR - Failed to execute job 40 for task test_conn (update only works with $ operators; 61319)
[2022-08-04 12:22:14,420] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-04 12:22:14,433] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
